Watching: '/home/cest/Workspace/evatutor/src/evatutor' 
'/home/cest/Workspace/evatutor/src/evatutor'

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Watching: '/home/cest/Workspace/evatutor/src/evatutor' 
'/home/cest/Workspace/evatutor/src/evatutor'

/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
Reloading service failed with the following exception: 
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/utils.py", line 208, in watchfn
    module = importlib.import_module(reloader.watch_module_name)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cest/Workspace/evatutor/src/evatutor/service.py", line 54
    label=""ðŸ”„",
            ^
SyntaxError: invalid character in identifier
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/routes.py", line 615, in predict
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 667
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 667
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/routes.py", line 615, in predict
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 667
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 667
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/routes.py", line 615, in predict
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 667
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 667
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/routes.py", line 615, in predict
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 667
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 667
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/routes.py", line 615, in predict
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 667
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 667
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
Reloading service failed with the following exception: 
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/utils.py", line 208, in watchfn
    module = importlib.import_module(reloader.watch_module_name)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cest/Workspace/evatutor/src/evatutor/service.py", line 54
    submit_btn="ðŸ“¨",,
                   ^
SyntaxError: invalid syntax
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/base.py:188: UserWarning: 'scale' value should be an integer. Using 0.1 will cause issues.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/routes.py", line 615, in predict
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 709
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 709
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/routes.py", line 615, in predict
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 709
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 709
Changes detected in: /home/cest/Workspace/evatutor/src/evatutor/service.py
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/components/dropdown.py:173: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 0 or set allow_custom_value=True.
  warnings.warn(
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/routes.py", line 615, in predict
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 751
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 751
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/routes.py", line 615, in predict
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 751
Traceback (most recent call last):
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1655, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/blocks.py", line 1356, in preprocess_data
    processed_input.append(state[input_id])
  File "/home/cest/.conda/envs/evatutor/lib/python3.8/site-packages/gradio/state_holder.py", line 46, in __getitem__
    block = self.blocks.blocks[key]
KeyError: 751
